eredes:
  nif: ${{ secrets.EREDES_NIF }}
  pwd: ${{ secrets.EREDES_PASSWORD }}
  cpe: ${{ secrets.EREDES_CPE }}

influxdb:
  # url to InfluxDB.  e.g. http://localhost or https://influxdb.my-domain.com
  host: http://localhost
  # default port is 8086
  port: 8086
  bucket: <my-influx-bucket>
  org: <my-influx-org>
  # access token with write access
  token: <token>
