name: E-Redes Scraper
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Navegador Virtual
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Testar Ferramentas
        run: echo "O navegador virtual foi instalado com sucesso!"
